### ISSUE TITLE
Why is this not available on Firefox any more?

### ISSUE THREAD

**Issue by MrGoatsy** [fcapano/Edit-This-Cookie#247]
I used to use this for Firefox but I deleted it today because my extensions were broken but I can't find it any more.

Why did it get deleted from the add-on site for Firefox?

**Comment by AnneTheAgile** [comment]
Firefox changed the entire language/format. 
So a rewrite is probably needed since this one is old - NB though I did not verify for this plugin, I just note it is not recently updated. 

Porting a legacy Firefox extension | Extension Workshop: https://extensionworkshop.com/documentation/develop/porting-a-legacy-firefox-extension/
````
If you have developed a Firefox extension using XUL/XPCOM or the Add-on SDK, this page will help you migrate your extension to use WebExtensions APIs. The standard to build extensions for Firefox is to use WebExtensions APIs. It will be the only type of extension supported in Firefox by the end of November 2017 with the release of Firefox 57.

Support for extensions using XUL/XPCOM or the Add-on SDK was removed in Firefox 57, released November 2017. As there is no supported version of Firefox enabling these technologies, this page will be removed by December 2020.
````

**Comment by kasbah** [comment]
You can probably just add the Chrome extension as a Firefox extension as the APIs are almost exactly the same now. 

That's what I did for my extension: https://github.com/kitspace/1clickBOM

**Comment by fyhtma** [comment]
https://addons.mozilla.org/en-US/firefox/addon/editthiscookie-lastest-edition/

**Comment by MrGoatsy** [comment]
Nice malware addon.
