### ISSUE TITLE
Rules for blocking cookies

### ISSUE THREAD

**Issue by WeetchKing** [fcapano/Edit-This-Cookie#83]
Is there anyway I can block cookies using rules instead of adding them manually?

Something like this:

cookie domain:
example.com

cookie name:
example_posts_*

action:
block

**Comment by chrissearle** [comment]
Looks like filterMatchesCookie needs attention for this:

```js
function filterMatchesCookie(rule, name, domain, value){
	var ruleDomainReg = new RegExp(rule.domain);
    if(rule.domain!=undefined && domain.match(ruleDomainReg) == null){
        return false
    }
    if(rule.name!=undefined && name!=rule.name){
        return false
    }
    if(rule.value!=undefined && value!=rule.value){
        return false
    }
    return true
}
```

So - regex on domain works but not on name.

As far as I can tell - this is being called from background.js (about line 99) when checking for blocked.

I could really do with this too - I have a site I use that appends a changing ID to two different cookies that I'd like to block.

**Comment by djbclark** [comment]
So it looks like this is fixed in the code up at:

https://github.com/fcapano/Edit-This-Cookie/blob/a171de3d3d3dfce66852172ecaf3be711de2c7c9/js/utils.js#L109

But not in the version 1.4.1 (ID: fngmhnnpilhplaeedifhccceomclgfbg) as is installed as of Wed, Jul 26, 2017 via chrome. It looks like for some reason the version available via chrome hasn't been updated since September 28, 2014 so this makes sense.

I tried just cut-and-pasting the new function but that didn't work.
